[package]
name = "hello_world_os"
version = "0.1.0"
authors = ["Band Protocol <dev@bandprotocol.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
owasm-kit = "0.3.0"
obi = "0.0.2"
